// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package queries

import (
	"time"
)

type Account struct {
	Name              string
	Index             int32
	Xpub              string
	DerivationPath    string
	NextExternalIndex int32
	NextInternalIndex int32
	FkWalletID        string
}

type AccountScriptInfo struct {
	Script         string
	DerivationPath string
	FkAccountName  string
}

type Transaction struct {
	TxID        string
	TxHex       string
	BlockHash   string
	BlockHeight int32
}

type TxInputAccount struct {
	ID          int32
	AccountName string
	TxID        string
}

type Utxo struct {
	ID              int32
	TxID            string
	Vout            int32
	Value           int64
	Asset           string
	ValueCommitment []byte
	AssetCommitment []byte
	ValueBlinder    []byte
	AssetBlinder    []byte
	Script          []byte
	Nonce           []byte
	RangeProof      []byte
	SurjectionProof []byte
	AccountName     string
	LockTimestamp   time.Time
}

type UtxoStatus struct {
	ID          int32
	BlockHeight int32
	BlockTime   time.Time
	BlockHash   string
	Status      int32
	FkUtxoID    int32
}

type Wallet struct {
	ID                  string
	EncryptedMnemonic   []byte
	PasswordHash        []byte
	BirthdayBlockHeight int32
	RootPath            string
	NetworkName         string
	NextAccountIndex    int32
}
