#!/bin/bash

SRC_DIR=./api-spec/protobuf
DST_DIR=./api-spec/protobuf/gen

## loop through the array
for current in "wallet" "account" "transaction" "notification"; do
  protoc -I=$SRC_DIR \
  --go_out=$DST_DIR/$current --go_opt=paths=source_relative \
  --go-grpc_out=$DST_DIR/$current --go-grpc_opt=paths=source_relative \
  $SRC_DIR/$current.proto
done